server:
  port: 18081

spring:
  profiles:
    active: dev

  jpa:
    generate-ddl: 'true'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
